### PR TITLE
Bigger powerups and louder heal sound

### PR DESCRIPTION
**Pull request by triszt4n**
Allow me to introduce:

# bigger power up icons and 

###### *louder heal sound*

### CODE REVIEW

**Review by vercibar — APPROVED** [review]
image

**Review by poiuztrewq1 — APPROVED** [review]
look-at-it-qqig7q

**Comment by triszt4n** [comment]
image

**Review by tetsuchii — APPROVED** [review]
538788c1bfb44117c410f8d9fd28f330

**Pull request merged**
