### PR TITLE
Powerup enhancment

### LINKED ISSUE #82: Add effects on player powerup is active
* Aura around them if shield is active
* have flames going from the back if supermode is active

### LINKED ISSUE #98: When continuing after dying, the powerups should be resetted
* Reset the FIFO
* Reset the current effect (e.g.: the hologram should die)

### PR DESCRIPTION
**Pull request by poiuztrewq1**
Utolsó pull request
closes #82 
closes #98

### CODE REVIEW

**Review by triszt4n — APPROVED** [review]
image

**Comment by poiuztrewq1** [comment]
finsih

**Review by vercibar — APPROVED** [review]
image

**Comment by tetsuchii** [comment]
3d80c61f164d38b1a0fce2853d659a9d

**Review by tetsuchii — APPROVED** [review]

**Pull request merged**
